//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSimulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class simulation
    {
        public short id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<short> duration { get; set; }
        public Nullable<double> payment { get; set; }
        public string date { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string bankId { get; set; }
        public string loanType { get; set; }
    }
}
